### ISSUE TITLE
Pins inexactes dans le fichier poids_4LC.ino

### ISSUE THREAD

**Issue by mareths** [mareths/suisTesAbeilles#2]
Dans le fichier [poids_4LC.ino](https://github.com/mareths/suisTesAbeilles/blob/master/sources/poids/poids_4LC.ino), peux-tu adapter les 2 pins en entrés aux pins Digital 10 et 11 conformément au schéma de câblage.

**Comment by ouvriere** [comment]
programme modifié pour correspondre au schema
