### ISSUE TITLE
lors du demarrage, envoyer un premier paquet de mesures

### ISSUE THREAD

**Issue by ouvriere** [mareths/suisTesAbeilles#21]
lorsqu on demarre l airboard ou qu il y a une initialisation, il faudrait envoyer un premier lot de mesure.
ca permet de valider que c opérationnel, d avoir immediatement un premier lot d indicateurs au lieu d attendre la premiere tempo qui peut etre de plusieurs heures.

**Comment by mareths** [comment]
A tester

**Comment by ouvriere** [comment]
testé ok
