### ISSUE TITLE
integrer un capteur d'humidité exterieur

### ISSUE THREAD

**Issue by ouvriere** [mareths/suisTesAbeilles#33]
afin d avoir un différentiel entre l intérieure et l extérieure de la ruche.
il faudrait un capteur qui réunisse, pression atmospherique, temperature et hygrometrie

**Comment by mareths** [comment]
https://www.amazon.fr/dp/B01MQQDP8D/ref=sr_1_14?ie=UTF8&qid=1481485812&sr=8-14&keywords=BME280
https://www.generationrobots.com/fr/402249-capteur-de-pression-humidit%C3%A9-et-de-temperature-adafruit-bme280.html

**Comment by ouvriere** [comment]
3 de ce type de commandés, on verra, a noter, fonctionne en spi:
https://www.amazon.fr/LANMU-CJMCU-280-Temp%C3%A9rature-barom%C3%A9trique-num%C3%A9rique/dp/B01G4T88VS/ref=sr_1_3?ie=UTF8&qid=1481490371&sr=8-3&keywords=BME280

**Comment by ouvriere** [comment]
commit du schema et du code pour le bme280, a integrer en lieu et place du bmp180
