### ISSUE TITLE
Envoi de messages plus rapidement à l'init du module

### ISSUE THREAD

**Issue by mareths** [mareths/suisTesAbeilles#37]
Afin d’être sur que tout fonctionne correctement après avoir allumé le module, et l'avoir disposé sur la ruche, nous souhaitons envoyé les premiers messages sur un intervalle de temps plus court, afin d’être sur que tout fonctionne correctement sans attendre plusieurs heures avant de recevoir le message suivant.

**Comment by mareths** [comment]
https://github.com/mareths/suisTesAbeilles/commit/8ad9d87cfdd4dc437c4fc74a8fc8d5d5ca5225af

**Comment by ouvriere** [comment]
installée
evol essentielle!
