### ISSUE TITLE
Temperature negative

### ISSUE THREAD

**Issue by ouvriere** [mareths/suisTesAbeilles#4]
est ce que c bien pris en compte sur l'ensemble des capteurs?

**Comment by mareths** [comment]
Evolution à prendre en compte:
Pour le byte décrivant la partie entière de la température, n'utiliser que les 7 bits les plus à droite pour la valeur, et le 8ème bit le plus à gauche pour la partie négative ou positive de la température (1 = positif, 0 = négatif)

Dans le codec de décodage, trouver une formule, un algo permettant la bonne interprétation de cette température

**Comment by mareths** [comment]
Test a réaliser:
Mettre Airboard+Lora+un capteur de température dans un congel, relever la T° au moment de la mesure, et relever la mesure reçue par la plateforme

**Comment by ouvriere** [comment]
test fait, les capteurs rapportent une température négative.
cf dashboard 11h55
