### ISSUE TITLE
ds18b20 absent mais capture des mesures qd meme

### ISSUE THREAD

**Issue by ouvriere** [mareths/suisTesAbeilles#6]
Done
Unable to find address for Device 2
Go to sleep
[...]
DS18B20 sensor - temperatureDS18B20_1: 2075 - 8 27
DS18B20 sensor - temperatureDS18B20_2: 2100 - 8 52
DS18B20 sensor - temperatureDS18B20_3: 2100 - 8 52

**Comment by mareths** [comment]
Il y a juste 3 capteurs DS18B20, et le programme téléverser est identique à celui de la branche master ?

**Comment by mareths** [comment]
C'est toujours le device 2 qui donne pas son adresse ? Il faudrait televerser le programme en mode ds18b20_1 (decommente en début de programme le define correspondant et commenté le define ds18b20_3) puis ne l'exécuter qu'avec une des 3 spndss

**Comment by ouvriere** [comment]
le use case: j ai deux capteurs de connectés mais 3 dans le code. Forcement, un des 3 ne doit rien renvoyer.
1- c est le 2 qui n est pas détecté (donc 1 et 3 sont détectés), on s attend plutot à 1 et 2 et 3 non detecté (mais c pas ce qui me gêne)
2 - qd, il y a deux capteurs physique de connectés mais le code remonte des mesures pour les 3 capteurs, pourquoi il n y en a pas un sur les 3 capteurs à 0?

**Comment by mareths** [comment]
Il faut flaguer les ds18b20 à "détecté" ou "absent" au moment de l'appel à **sensors.getAddress**, et lors de la collecte des la température, fixer celle-ci à "100" pour ceux qui n'ont pas été détecté.

**Comment by mareths** [comment]
Ca compile, à tester

**Comment by ouvriere** [comment]
ca marche
